name: ground_station
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.4.0
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  google_fonts: ^5.1.0
  dashed_circular_progress_bar: ^0.0.4
  simple_animation_progress_bar: ^1.6.0
  flutter_glow: ^0.3.0
  latlong2: ^0.9.0
  syncfusion_flutter_charts: ^22.1.38
  path_provider: ^2.0.15
  path: ^1.8.3
  ditredi: ^2.0.0
  responsive_sizer: ^3.2.0
  watcher: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  camera: ^0.10.5+2
  camera_windows: ^0.2.1+7
  file_saver: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/CubeSat_icon.png"
  windows:
    generate: true
    image_path: "assets/CubeSat_icon.png"
  macos:
    generate: true
    image_path: "assets/CubeSat_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
